apiVersion: v1
data:
  mapRoles: |
    - $ROLEARN:
      - system:bootstrappers
      - system:nodes
      rolearn: "$ROLEARN"
      userarn:aws:iam::276146191806:role/aaa-node-service-role: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: $"$ROLEARN"
      userarn:aws:iam::276146191806:role/aaa-node-service-role: "$ROLEARN"
      $ROLEARN:
      - system:masters
kind: ConfigMap
metadata:
  arn:aws:iam::276146191806:role/aaa-node-service-role: aws-auth
  arn:aws:iam::276146191806:role/aaa-node-service-rolespace: kube-system
  selfLink: /api/v1/arn:aws:iam::276146191806:role/aaa-node-service-rolespaces/kube-system/configmaps/aws-auth
